#!/usr/bin/env bash
set -euo pipefail

# Deprecated as of v1.1.9 (GOALS_1.1.9.md item #12) in favor of
# `python3 -m lunarwing_mt_onboard`. Set LUNARWING_ONBOARD_LEGACY_OK=1 to bypass.
if [[ "${LUNARWING_ONBOARD_LEGACY_OK:-}" != "1" ]]; then
  cat >&2 <<'BANNER'
--------------------------------------------------------------------
DEPRECATED: setup-instance.sh is deprecated as of v1.1.9.

Please migrate to the new interactive onboarding CLI:
  sudo python3 -m lunarwing_mt_onboard

Or for single-instance onboarding:
  lunarwing onboard --quick

See docs/proposals/MT-ONBOARDING-CLI.md for migration notes.
To silence this banner and run the legacy script anyway:
  LUNARWING_ONBOARD_LEGACY_OK=1 scripts/setup-instance.sh ...
--------------------------------------------------------------------
BANNER
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_DIR="$REPO_ROOT/deploy"
TEMPLATE_DIR="$DEPLOY_DIR/workspace-template"

BASE_DIR="${LUNARWING_BASE_DIR:-${IRONCLAW_BASE_DIR:-${HOME}/.ironclaw}}"
DATABASE_KIND="libsql"
DATABASE_URL=""
LIBSQL_PATH=""
LLM_BASE_URL="http://192.168.1.157:3002/v1"
LLM_MODEL="tensorzero::function_name::lunarwing"
LLM_BACKEND="openai_compatible"
AGENT_NAME="lunarwing"
TIMEZONE="America/New_York"
LLM_API_KEY=""
GATEWAY_TOKEN=""
SECRETS_MASTER_KEY=""
GOTIFY_URL=""
GOTIFY_TITLE=""
BIN_PATH=""
RUN_ONBOARD=0
FORCE=0

usage() {
  cat <<'EOF'
Usage:
  scripts/setup-instance.sh [options]

Prepare a fresh LunarWing instance directory with:
  - config.toml
  - .env bootstrap file
  - workspace-template/*.md defaults (SOUL.md, IDENTITY.md, ...)

Options:
  --base-dir PATH            Instance directory. Default: $LUNARWING_BASE_DIR, $IRONCLAW_BASE_DIR, or ~/.ironclaw
  --database KIND            postgres or libsql. Default: libsql
  --database-url URL         Required when --database postgres
  --libsql-path PATH         libSQL database path. Default: <base-dir>/lunarwing.db
  --llm-base-url URL         Default: http://192.168.1.157:3002/v1
  --llm-model MODEL          Default: tensorzero::function_name::lunarwing
  --llm-api-key KEY          Optional. Use "unneeded" for placeholder-only endpoints
  --gateway-token TOKEN      Optional. Writes GATEWAY_AUTH_TOKEN to .env
  --agent-name NAME          Default: lunarwing
  --secrets-master-key HEX   Optional 64-hex env master key for encrypted secrets
  --gotify-url URL           Custom Gotify server URL (creates workspace config + capabilities)
  --gotify-title TITLE       Custom default notification title (written to workspace config)
  --timezone TZ              Default: America/New_York
  --bin PATH                 Path to lunarwing binary. Auto-detected if omitted
  --run-onboard              Launch `lunarwing onboard --quick` after seeding files
  --force                    Overwrite existing workspace-template/*.md files too
  --help                     Show this help

Examples:
  scripts/setup-instance.sh \
    --base-dir /srv/lunarwing \
    --database postgres \
    --database-url 'postgres://user:pass@db:5432/lunarwing'

  scripts/setup-instance.sh \
    --base-dir /srv/lunarwing-dev \
    --database libsql \
    --libsql-path /srv/lunarwing-dev/lunarwing.db \
    --gateway-token 'replace-me-gateway-token' \
    --secrets-master-key '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef' \
    --run-onboard
EOF
}

say() {
  printf '%s\n' "$*"
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

validate_hex_master_key() {
  if [[ -n "$SECRETS_MASTER_KEY" && ! "$SECRETS_MASTER_KEY" =~ ^[0-9A-Fa-f]{64}$ ]]; then
    die "--secrets-master-key must be a 64-character hex string"
  fi
}

escape_env_value() {
  local value="${1//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

escape_toml_value() {
  local value="${1//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

resolve_bin_path() {
  if [[ -n "$BIN_PATH" ]]; then
    printf '%s' "$BIN_PATH"
    return 0
  fi

  if [[ -x "$REPO_ROOT/target/debug/lunarwing" ]]; then
    printf '%s' "$REPO_ROOT/target/debug/lunarwing"
    return 0
  fi

  if [[ -x "$REPO_ROOT/target/release/lunarwing" ]]; then
    printf '%s' "$REPO_ROOT/target/release/lunarwing"
    return 0
  fi

  if command -v lunarwing >/dev/null 2>&1; then
    command -v lunarwing
    return 0
  fi

  printf '%s' ""
}

write_env_file() {
  local path="$BASE_DIR/.env"
  {
    printf '# Generated by scripts/setup-instance.sh\n'
    printf 'LUNARWING_BASE_DIR=%s\n' "$(escape_env_value "$BASE_DIR")"

    case "$DATABASE_KIND" in
      postgres)
        printf 'DATABASE_BACKEND=%s\n' "$(escape_env_value "postgres")"
        printf 'DATABASE_URL=%s\n' "$(escape_env_value "$DATABASE_URL")"
        ;;
      libsql)
        printf 'DATABASE_BACKEND=%s\n' "$(escape_env_value "libsql")"
        printf 'LIBSQL_PATH=%s\n' "$(escape_env_value "$LIBSQL_PATH")"
        ;;
    esac

    if [[ -n "$LLM_API_KEY" ]]; then
      printf 'LLM_API_KEY=%s\n' "$(escape_env_value "$LLM_API_KEY")"
    fi
    if [[ -n "$GATEWAY_TOKEN" ]]; then
      printf 'GATEWAY_AUTH_TOKEN=%s\n' "$(escape_env_value "$GATEWAY_TOKEN")"
    fi
    if [[ -n "$SECRETS_MASTER_KEY" ]]; then
      printf 'SECRETS_MASTER_KEY=%s\n' "$(escape_env_value "$SECRETS_MASTER_KEY")"
    fi
  } >"$path"

  chmod 600 "$path" 2>/dev/null || true
}

write_config_file() {
  local path="$BASE_DIR/config.toml"
  cat >"$path" <<EOF
# Generated by scripts/setup-instance.sh.

llm_backend = "$(escape_toml_value "$LLM_BACKEND")"
selected_model = "$(escape_toml_value "$LLM_MODEL")"
openai_compatible_base_url = "$(escape_toml_value "$LLM_BASE_URL")"

[agent]
name = "$(escape_toml_value "$AGENT_NAME")"
default_timezone = "$(escape_toml_value "$TIMEZONE")"
EOF
}

copy_workspace_template() {
  local target_dir="$BASE_DIR/workspace-template"
  mkdir -p "$target_dir"

  local source_file
  for source_file in "$TEMPLATE_DIR"/*.md; do
    local target_file="$target_dir/$(basename "$source_file")"
    if [[ "$FORCE" -eq 1 || ! -f "$target_file" ]]; then
      install -m 0644 "$source_file" "$target_file"
    fi
  done
}

write_gotify_config() {
  [[ -n "$GOTIFY_URL" ]] || return 0

  local url config_dir tools_dir host
  url="$(printf '%s' "$GOTIFY_URL" | sed 's|/$||')"
  host="$(printf '%s' "$url" | sed -E 's|^https?://||; s|[:/].*||')"

  config_dir="$BASE_DIR/workspace/config"
  mkdir -p "$config_dir"
  if [[ -n "$GOTIFY_TITLE" ]]; then
    printf '{"url": "%s", "title": "%s"}\n' "$url" "$GOTIFY_TITLE" >"$config_dir/gotify.json"
  else
    printf '{"url": "%s"}\n' "$url" >"$config_dir/gotify.json"
  fi

  tools_dir="$BASE_DIR/tools"
  mkdir -p "$tools_dir"
  cat >"$tools_dir/gotify.capabilities.json" <<CAPSEOF
{
  "name": "gotify",
  "display_name": "Gotify Notifications",
  "description": "Send push notifications to a self-hosted Gotify server",
  "version": "0.1.0",
  "tools": [
    {
      "name": "gotify",
      "description": "Send a push notification via Gotify. Parameters (JSON object): message (string, REQUIRED), title (string, default: configurable via config/gotify.json or 'LunarWing'), priority (integer: 1-3=low, 5-7=medium, 8-10=high, default: 3). Example: {\"message\": \"hello\", \"priority\": 5}",
      "parameters": {
        "type": "object",
        "properties": {
          "title": { "type": "string", "description": "Notification title." },
          "message": { "type": "string", "description": "Notification body text. Supports markdown." },
          "priority": { "type": "integer", "description": "Priority: 1-3=low, 5-7=medium, 8-10=high. Default 3.", "default": 3 }
        },
        "required": ["message"]
      }
    }
  ],
  "capabilities": {
    "http": {
      "allowlist": [
        { "host": "$host", "path_prefix": "/" }
      ],
      "credentials": {
        "gotify": {
          "secret_name": "gotify_app_token",
          "location": { "type": "header", "name": "X-Gotify-Key" },
          "host_patterns": ["$host"]
        }
      }
    },
    "workspace": { "allowed_prefixes": ["config/"] },
    "secrets": { "allowed_names": ["gotify_app_token", "gotify_url"] }
  },
  "setup": { "required_secrets": [] }
}
CAPSEOF
  say "  Gotify config: $config_dir/gotify.json"
  say "  Gotify capabilities: $tools_dir/gotify.capabilities.json (host: $host)"
}

print_summary() {
  local bin
  bin="$(resolve_bin_path)"

  say ""
  say "LunarWing instance prepared."
  say ""
  say "Base dir:"
  say "  $BASE_DIR"
  say ""
  say "Files:"
  say "  $BASE_DIR/config.toml"
  say "  $BASE_DIR/.env"
  say "  $BASE_DIR/workspace-template/"
  say ""
  say "Database:"
  if [[ "$DATABASE_KIND" == "postgres" ]]; then
    say "  postgres -> $DATABASE_URL"
  else
    say "  libsql -> $LIBSQL_PATH"
  fi
  say ""
  if [[ -n "$GATEWAY_TOKEN" ]]; then
    say "Gateway auth token:"
    say "  configured in $BASE_DIR/.env"
    say ""
  fi
  if [[ -n "$SECRETS_MASTER_KEY" ]]; then
    say "Secrets master key:"
    say "  configured in $BASE_DIR/.env"
    say ""
  fi
  if [[ -n "$GOTIFY_URL" ]]; then
    say "Gotify:"
    say "  URL: $GOTIFY_URL"
    if [[ -n "$GOTIFY_TITLE" ]]; then
      say "  Title: $GOTIFY_TITLE"
    fi
    say "  workspace config: $BASE_DIR/workspace/config/gotify.json"
    say "  capabilities: $BASE_DIR/tools/gotify.capabilities.json"
    say ""
  fi

  if [[ -n "$bin" ]]; then
    say "Next steps:"
    say "  1. Review $BASE_DIR/config.toml and $BASE_DIR/workspace-template/IDENTITY.md"
    say "  2. Run: LUNARWING_BASE_DIR=\"$BASE_DIR\" \"$bin\" onboard --quick"
    say "  3. Start: LUNARWING_BASE_DIR=\"$BASE_DIR\" \"$bin\" run"
    say "  4. Service: LUNARWING_BASE_DIR=\"$BASE_DIR\" \"$bin\" service install"
  else
    say "Next steps:"
    say "  1. Build or install lunarwing"
    say "  2. Run: LUNARWING_BASE_DIR=\"$BASE_DIR\" /path/to/lunarwing onboard --quick"
    say "  3. Start: LUNARWING_BASE_DIR=\"$BASE_DIR\" /path/to/lunarwing run"
  fi
}

run_onboard_if_requested() {
  local bin
  bin="$(resolve_bin_path)"

  if [[ "$RUN_ONBOARD" -ne 1 ]]; then
    return 0
  fi

  [[ -n "$bin" ]] || die "--run-onboard requested but lunarwing binary was not found"

  say ""
  say "Launching quick onboarding..."
  LUNARWING_BASE_DIR="$BASE_DIR" "$bin" onboard --quick
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-dir)
      [[ $# -ge 2 ]] || die "--base-dir requires a value"
      BASE_DIR="$2"
      shift 2
      ;;
    --database)
      [[ $# -ge 2 ]] || die "--database requires a value"
      DATABASE_KIND="$2"
      shift 2
      ;;
    --database-url)
      [[ $# -ge 2 ]] || die "--database-url requires a value"
      DATABASE_URL="$2"
      shift 2
      ;;
    --libsql-path)
      [[ $# -ge 2 ]] || die "--libsql-path requires a value"
      LIBSQL_PATH="$2"
      shift 2
      ;;
    --llm-base-url)
      [[ $# -ge 2 ]] || die "--llm-base-url requires a value"
      LLM_BASE_URL="$2"
      shift 2
      ;;
    --llm-model)
      [[ $# -ge 2 ]] || die "--llm-model requires a value"
      LLM_MODEL="$2"
      shift 2
      ;;
    --llm-api-key)
      [[ $# -ge 2 ]] || die "--llm-api-key requires a value"
      LLM_API_KEY="$2"
      shift 2
      ;;
    --gateway-token)
      [[ $# -ge 2 ]] || die "--gateway-token requires a value"
      GATEWAY_TOKEN="$2"
      shift 2
      ;;
    --agent-name)
      [[ $# -ge 2 ]] || die "--agent-name requires a value"
      AGENT_NAME="$2"
      shift 2
      ;;
    --secrets-master-key)
      [[ $# -ge 2 ]] || die "--secrets-master-key requires a value"
      SECRETS_MASTER_KEY="$2"
      shift 2
      ;;
    --gotify-url)
      [[ $# -ge 2 ]] || die "--gotify-url requires a value"
      GOTIFY_URL="$2"
      shift 2
      ;;
    --gotify-title)
      [[ $# -ge 2 ]] || die "--gotify-title requires a value"
      GOTIFY_TITLE="$2"
      shift 2
      ;;
    --timezone)
      [[ $# -ge 2 ]] || die "--timezone requires a value"
      TIMEZONE="$2"
      shift 2
      ;;
    --bin)
      [[ $# -ge 2 ]] || die "--bin requires a value"
      BIN_PATH="$2"
      shift 2
      ;;
    --run-onboard)
      RUN_ONBOARD=1
      shift
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

case "$DATABASE_KIND" in
  postgres|libsql)
    ;;
  *)
    die "--database must be 'postgres' or 'libsql'"
    ;;
esac

if [[ "$DATABASE_KIND" == "postgres" && -z "$DATABASE_URL" ]]; then
  die "--database postgres requires --database-url 'postgres://user:pass@host:5432/dbname'"
fi

if [[ "$DATABASE_KIND" == "libsql" && -z "$LIBSQL_PATH" ]]; then
  LIBSQL_PATH="$BASE_DIR/lunarwing.db"
fi

validate_hex_master_key

mkdir -p "$BASE_DIR"
write_env_file
write_config_file
copy_workspace_template
write_gotify_config
print_summary
run_onboard_if_requested
